### ISSUE TITLE
Decide on a name for this tool

### ISSUE THREAD

**Issue by cmungall** [linkml/schemasheets#1]
Currently fairstructure, but can change

Could go for generic, e.g. schemasheets, sheets2linkml...?

**Comment by sujaypatil96** [comment]
I presume this package will eventually be deployed to PyPI. We can't use the name [sheet2linkml](https://pypi.org/project/sheet2linkml/) since we already have a CCDH specific package with the same name. We can however use the name `sheets2linkml` as suggested above. Or perhaps even `gsheet2linkml`.

**Comment by cmungall** [comment]
decided on email thread: it is now schemasheets
