### ISSUE TITLE
is there a working example of applying annotations with schemasheets

### ISSUE THREAD

**Issue by turbomam** [linkml/schemasheets#14]
I see them in the MIxS example sheet but I haven't been successful in converting that

**Comment by cmungall** [comment]
See

https://docs.google.com/spreadsheets/d/1wVoaiFg47aT9YWNeRfTZ8tYHN8s8PAuDx5i2HUcDpvQ/edit#gid=55566104

say you want an annotation `foo`:

the column config would be:

|foo|
|---|
|annotations|
|inner_key: foo|

then simply have a cell value `bar` and it will set annotatiobs['foo'] = bar
