### ISSUE TITLE
Classes not populated with slots as expected

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/schemasheets#34]
Using the personinfo.yaml schema as an example, the export functionality doesn't create tsv file with the Person class containing its slots as expected.

**Comment by sierra-moxon** [comment]
I am assuming this has been fixed; when we used the schemasheets repo at the recent phenomics first hackathon, it produced appropriate YAML.  I imagine we still have some work to do on our TSV generation (esp around multivalued slots?), but I think there are other tickets for that specifically in linkml vs. schemasheets?  please reopen if I got this incorrect?  :)
