### ISSUE TITLE
add a column for directing rows to different YAML files

### ISSUE THREAD

**Issue by turbomam** [linkml/schemasheets#65]
The NMDC and MIxS models (and presumably many more) consist of several YAML files.

In order to support faithful round-tripping, we could add a column that specifies that a row from a template should to to a particular YAML file when running `sheets2linkml`

**Comment by sierra-moxon** [comment]
I think this is already implemented (types vs. enums vs. slots vs. classes tabs?) closing, reopen if necessary :)

**Comment by turbomam** [comment]
This hasn't been implemented, but it might not be a high priority. 

If one has TSV files for types vs. enums vs. slots vs. classes etc., sheets2linkml will compile them down to one YAML file.

The MIxS schema currently has many YAML modules. We are moving towards a shemasheets implementation, but that will generate a single YAML file, and some contributors may feel disoriented by that or may not like working with such a large file.

I was hoping that sheets2linkml could be configured to emit different parts of the model to different YAML files.
