### ISSUE TITLE
three tests failing in main

### ISSUE THREAD

**Issue by turbomam** [linkml/schemasheets#68]
> FAILED tests/test_schema_exporter.py::test_types - schemasheets.schemamaker.SchemaSheetRowException: Error in line 2, row={'Type': '', 'base': '', 'uri': '', 'Desc': 'my string', 'Extends': 'string'}
FAILED tests/test_schemamaker.py::test_types - AttributeError: 'TypeDefinition' object has no attribute 'type'
FAILED tests/test_schemamaker.py::test_combined - AttributeError: 'TypeDefinition' object has no attribute 'type'

**Comment by cmungall** [comment]
I ran a test to check this, #71, and the test suite passes

is this still an issue?
